// Code generated by llcppg; DO NOT EDIT.

package yyjson

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const YYJSON_DISABLE_READER = 0
const YYJSON_DISABLE_WRITER = 0
const YYJSON_DISABLE_INCR_READER = 0
const YYJSON_DISABLE_FILE = 0
const YYJSON_DISABLE_UTILS = 0
const YYJSON_DISABLE_FAST_FP_CONV = 0
const YYJSON_DISABLE_NON_STANDARD = 0
const YYJSON_DISABLE_UTF8_VALIDATION = 0
const YYJSON_READER_DEPTH_LIMIT = 0
const YYJSON_WRITER_DEPTH_LIMIT = 0
const YYJSON_FREESTANDING = 0
const YYJSON_MSC_VER = 0
const YYJSON_IS_REAL_GCC = 0
const YYJSON_CPP_VER = 0
const YYJSON_HAS_CONSTANT_P = 1
const YYJSON_U64_TO_F64_NO_IMPL = 0
const YYJSON_VERSION_MAJOR = 0
const YYJSON_VERSION_MINOR = 13
const YYJSON_VERSION_PATCH = 0
const YYJSON_VERSION_HEX = 3328
const YYJSON_VERSION_STRING = "0.13.0"
const YYJSON_PADDING_SIZE = 4
const YYJSON_WRITE_FP_FLAG_BITS = 8
const YYJSON_WRITE_FP_PREC_BITS = 4

// Type of a JSON value (3 bit).
type YyjsonType = c.Uint8T

// Subtype of a JSON value (2 bit).
type YyjsonSubtype = c.Uint8T

// A memory allocator.
//
// Typically you don't need to use it, unless you want to customize your own
// memory allocator.
//
// llgo:type C
type YyjsonAlc struct {
	Malloc  func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.SizeT) unsafe.Pointer
	Realloc func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 unsafe.Pointer, _llcppg_param3 c.SizeT, _llcppg_param4 c.SizeT) unsafe.Pointer
	Free    func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 unsafe.Pointer)
	Ctx     unsafe.Pointer
}
type YyjsonDoc struct {
	Root    *YyjsonVal
	Alc     YyjsonAlc
	DatRead c.SizeT
	ValRead c.SizeT
	StrPool *c.Char
}

// Immutable JSON value, 16 bytes.
type YyjsonVal struct {
	Tag c.Uint64T
	Uni YyjsonValUni
}
type YyjsonMutDoc struct {
	Root    *YyjsonMutVal
	Alc     YyjsonAlc
	StrPool YyjsonStrPool
	ValPool YyjsonValPool
}

// Mutable JSON value, 24 bytes.
// The 'tag' and 'uni' fields are the same as immutable value.
// The 'next' field links all elements inside the container to be a cycle.
type YyjsonMutVal struct {
	Tag  c.Uint64T
	Uni  YyjsonValUni
	Next *YyjsonMutVal
}

// Run-time options for JSON reader.
type YyjsonReadFlag = c.Uint32T

// Result code for JSON reader.
type YyjsonReadCode = c.Uint32T

// Error information for JSON reader.
type YyjsonReadErr struct {
	Code YyjsonReadCode
	Msg  *c.Char
	Pos  c.SizeT
}
type YyjsonIncrState struct {
}

// Run-time options for JSON writer.
type YyjsonWriteFlag = c.Uint32T

// Result code for JSON writer
type YyjsonWriteCode = c.Uint32T

// Error information for JSON writer.
type YyjsonWriteErr struct {
	Code YyjsonWriteCode
	Msg  *c.Char
}

// A JSON array iterator.
//
// @b Example
// @code
// yyjson_val *val;
// yyjson_arr_iter iter = yyjson_arr_iter_with(arr);
// while ((val = yyjson_arr_iter_next(&iter))) {
// your_func(val);
// }
// @endcode
type YyjsonArrIter struct {
	Idx c.SizeT
	Max c.SizeT
	Cur *YyjsonVal
}

// A JSON object iterator.
//
// @b Example
// @code
// yyjson_val *key, *val;
// yyjson_obj_iter iter = yyjson_obj_iter_with(obj);
// while ((key = yyjson_obj_iter_next(&iter))) {
// val = yyjson_obj_iter_get_val(key);
// your_func(key, val);
// }
// @endcode
//
// If the ordering of the keys is known at compile-time, you can use this method
// to speed up value lookups:
// @code
// {"k1":1, "k2": 3, "k3": 3}
// yyjson_val *key, *val;
// yyjson_obj_iter iter = yyjson_obj_iter_with(obj);
// yyjson_val *v1 = yyjson_obj_iter_get(&iter, "k1");
// yyjson_val *v3 = yyjson_obj_iter_get(&iter, "k3");
// @endcode
// @see yyjson_obj_iter_get() and yyjson_obj_iter_getn()
type YyjsonObjIter struct {
	Idx c.SizeT
	Max c.SizeT
	Cur *YyjsonVal
	Obj *YyjsonVal
}

// A mutable JSON array iterator.
//
// @warning You should not modify the array while iterating over it, but you can
// use `yyjson_mut_arr_iter_remove()` to remove current value.
//
// @b Example
// @code
// yyjson_mut_val *val;
// yyjson_mut_arr_iter iter = yyjson_mut_arr_iter_with(arr);
// while ((val = yyjson_mut_arr_iter_next(&iter))) {
// your_func(val);
// if (your_val_is_unused(val)) {
// yyjson_mut_arr_iter_remove(&iter);
// }
// }
// @endcode
type YyjsonMutArrIter struct {
	Idx c.SizeT
	Max c.SizeT
	Cur *YyjsonMutVal
	Pre *YyjsonMutVal
	Arr *YyjsonMutVal
}

// A mutable JSON object iterator.
//
// @warning You should not modify the object while iterating over it, but you can
// use `yyjson_mut_obj_iter_remove()` to remove current value.
//
// @b Example
// @code
// yyjson_mut_val *key, *val;
// yyjson_mut_obj_iter iter = yyjson_mut_obj_iter_with(obj);
// while ((key = yyjson_mut_obj_iter_next(&iter))) {
// val = yyjson_mut_obj_iter_get_val(key);
// your_func(key, val);
// if (your_val_is_unused(key, val)) {
// yyjson_mut_obj_iter_remove(&iter);
// }
// }
// @endcode
//
// If the ordering of the keys is known at compile-time, you can use this method
// to speed up value lookups:
// @code
// {"k1":1, "k2": 3, "k3": 3}
// yyjson_mut_val *key, *val;
// yyjson_mut_obj_iter iter = yyjson_mut_obj_iter_with(obj);
// yyjson_mut_val *v1 = yyjson_mut_obj_iter_get(&iter, "k1");
// yyjson_mut_val *v3 = yyjson_mut_obj_iter_get(&iter, "k3");
// @endcode
// @see `yyjson_mut_obj_iter_get()` and `yyjson_mut_obj_iter_getn()`
type YyjsonMutObjIter struct {
	Idx c.SizeT
	Max c.SizeT
	Cur *YyjsonMutVal
	Pre *YyjsonMutVal
	Obj *YyjsonMutVal
}

// JSON Pointer error code.
type YyjsonPtrCode = c.Uint32T

// Error information for JSON pointer.
type YyjsonPtrErr struct {
	Code YyjsonPtrCode
	Msg  *c.Char
	Pos  c.SizeT
}

// A context for JSON pointer operation.
//
// This struct stores the context of JSON Pointer operation result. The struct
// can be used with three helper functions: `ctx_append()`, `ctx_replace()`, and
// `ctx_remove()`, which perform the corresponding operations on the container
// without re-parsing the JSON Pointer.
//
// For example:
// @code
// doc before: {"a":[0,1,null]}
// ptr: "/a/2"
// val = yyjson_mut_doc_ptr_getx(doc, ptr, strlen(ptr), &ctx, &err);
// if (yyjson_is_null(val)) {
// yyjson_ptr_ctx_remove(&ctx);
// }
// doc after: {"a":[0,1]}
// @endcode
type YyjsonPtrCtx struct {
	Ctn *YyjsonMutVal
	Pre *YyjsonMutVal
	Old *YyjsonMutVal
}

// Result code for JSON patch.
type YyjsonPatchCode = c.Uint32T

// Error information for JSON patch.
type YyjsonPatchErr struct {
	Code YyjsonPatchCode
	Idx  c.SizeT
	Msg  *c.Char
	Ptr  YyjsonPtrErr
}
type YyjsonValUni struct {
	_xgo_union [1]uint64
}

// A memory chunk in string memory pool.
type YyjsonStrChunk struct {
	Next      *YyjsonStrChunk
	ChunkSize c.SizeT
}

// A memory pool to hold all strings in a mutable document.
type YyjsonStrPool struct {
	Cur          *c.Char
	End          *c.Char
	ChunkSize    c.SizeT
	ChunkSizeMax c.SizeT
	Chunks       *YyjsonStrChunk
}

// A memory chunk in value memory pool.
// `sizeof(yyjson_val_chunk)` should not be larger than `sizeof(yyjson_mut_val)`.
type YyjsonValChunk struct {
	Next      *YyjsonValChunk
	ChunkSize c.SizeT
}

// A memory pool to hold all values in a mutable document.
type YyjsonValPool struct {
	Cur          *YyjsonMutVal
	End          *YyjsonMutVal
	ChunkSize    c.SizeT
	ChunkSizeMax c.SizeT
	Chunks       *YyjsonValChunk
}

// The version of yyjson in hex, same as `YYJSON_VERSION_HEX`.
//
//go:linkname YyjsonVersion C.yyjson_version
func YyjsonVersion() c.Uint32T

// A pool allocator uses fixed length pre-allocated memory.
//
// This allocator may be used to avoid malloc/realloc calls. The pre-allocated
// memory should be held by the caller. The maximum amount of memory required to
// read a JSON can be calculated using the `yyjson_read_max_memory_usage()`
// function, but the amount of memory required to write a JSON cannot be directly
// calculated.
//
// This is not a general-purpose allocator. It is designed to handle a single JSON
// document at a time. If it is used for overly complex memory tasks, such as
// parsing multiple JSON documents using the same allocator but releasing only a
// few of them, it may cause memory fragmentation, resulting in performance
// degradation and memory waste.
//
// @param alc The allocator to be initialized.
// If `alc` is NULL, returns false.
// If `buf` or `size` is invalid, this will be set to an empty allocator.
// @param buf The buffer memory for this allocator.
// If `buf` is NULL, returns false.
// @param size The size of `buf`, in bytes.
// If `size` is less than 8 words (32/64 bytes on 32/64-bit OS),
// returns false.
// @return true if the `alc` has been successfully initialized.
//
// @b Example
// @code
// parse JSON with stack memory
// char buf[1024];
// yyjson_alc alc;
// yyjson_alc_pool_init(&alc, buf, 1024);
//
// const char *json = "{\"name\":\"Helvetica\",\"size\":16}";
// yyjson_doc *doc = yyjson_read_opts(json, strlen(json), 0, &alc, NULL);
// the memory of `doc` is on the stack
// @endcode
//
// @warning This Allocator is not thread-safe.
//
// llgo:link (*YyjsonAlc).PoolInit C.yyjson_alc_pool_init
func (self *YyjsonAlc) PoolInit(buf unsafe.Pointer, size c.SizeT) bool {
	return false
}

// A dynamic allocator.
//
// This allocator has a similar usage to the pool allocator above. However, when
// there is not enough memory, this allocator will dynamically request more memory
// using libc's `malloc` function, and frees it all at once when it is destroyed.
//
// @return A new dynamic allocator, or NULL if memory allocation failed.
// @note The returned value should be freed with `yyjson_alc_dyn_free()`.
//
// @warning This Allocator is not thread-safe.
//
//go:linkname YyjsonAlcDynNew C.yyjson_alc_dyn_new
func YyjsonAlcDynNew() *YyjsonAlc

// Free a dynamic allocator which is created by `yyjson_alc_dyn_new()`.
// @param alc The dynamic allocator to be destroyed.
//
// llgo:link (*YyjsonAlc).DynFree C.yyjson_alc_dyn_free
func (self *YyjsonAlc) DynFree() {
}

// Locate the line and column number for a byte position in a string.
// This can be used to get better description for error position.
//
// @param str The input string.
// @param len The byte length of the input string.
// @param pos The byte position within the input string.
// @param line A pointer to receive the line number, starting from 1.
// @param col  A pointer to receive the column number, starting from 1.
// @param chr  A pointer to receive the character index, starting from 0.
// @return true on success, false if `str` is NULL or `pos` is out of bounds.
// @note Line/column/character are calculated based on Unicode characters for
// compatibility with text editors. For multi-byte UTF-8 characters,
// the returned value may not directly correspond to the byte position.
//
//go:linkname YyjsonLocatePos C.yyjson_locate_pos
func YyjsonLocatePos(str *c.Char, len c.SizeT, pos c.SizeT, line *c.SizeT, col *c.SizeT, chr *c.SizeT) bool

// Read JSON with options.
//
// This function is thread-safe when:
// 1. The `dat` is not modified by other threads.
// 2. The `alc` is thread-safe or NULL.
//
// @param dat The JSON data (UTF-8 without BOM), null-terminator is not required.
// If `dat` is NULL, returns NULL.
// The `dat` will not be modified without the flag `YYJSON_READ_INSITU`, so you
// can pass a `const char *` string and cast it to `char *` if you don't use
// the `YYJSON_READ_INSITU` flag.
// @param len The length of JSON data in bytes.
// If `len` is 0, returns NULL.
// @param flg The JSON read options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON reader.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON document, or NULL if an error occurs.
// When it's no longer needed, it should be freed with `yyjson_doc_free()`.
//
//go:linkname YyjsonReadOpts C.yyjson_read_opts
func YyjsonReadOpts(dat *c.Char, len c.SizeT, flg YyjsonReadFlag, alc *YyjsonAlc, err *YyjsonReadErr) *YyjsonDoc

// Read a JSON file.
//
// This function is thread-safe when:
// 1. The file is not modified by other threads.
// 2. The `alc` is thread-safe or NULL.
//
// @param path The JSON file's path.
// This should be a null-terminated string using the system's native encoding.
// If `path` is NULL or invalid, returns NULL.
// @param flg The JSON read options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON reader.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON document, or NULL if an error occurs.
// When it's no longer needed, it should be freed with `yyjson_doc_free()`.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to read.
//
//go:linkname YyjsonReadFile C.yyjson_read_file
func YyjsonReadFile(path *c.Char, flg YyjsonReadFlag, alc *YyjsonAlc, err *YyjsonReadErr) *YyjsonDoc

// Read JSON from a file pointer.
//
// @param fp The file pointer.
// The data will be read from the current position of the FILE to the end.
// If `fp` is NULL or invalid, returns NULL.
// @param flg The JSON read options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON reader.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON document, or NULL if an error occurs.
// When it's no longer needed, it should be freed with `yyjson_doc_free()`.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to read.
//
//go:linkname YyjsonReadFp C.yyjson_read_fp
func YyjsonReadFp(fp *c.FILE, flg YyjsonReadFlag, alc *YyjsonAlc, err *YyjsonReadErr) *YyjsonDoc

// Initialize state for incremental read.
//
// To read a large JSON document incrementally:
// 1. Call `yyjson_incr_new()` to create the state for incremental reading.
// 2. Call `yyjson_incr_read()` repeatedly.
// 3. Call `yyjson_incr_free()` to free the state.
//
// Note: The incremental JSON reader only supports standard JSON.
// Flags for non-standard features (e.g. comments, trailing commas) are ignored.
//
// @param buf The JSON data, null-terminator is not required.
// If `buf` is NULL, returns NULL.
// @param buf_len The length of the JSON data in `buf`.
// If using `YYJSON_READ_INSITU`, buf_len should not include the padding size.
// @param flg The JSON read options.
// Multiple options can be combined with `|` operator.
// @param alc The memory allocator used by JSON reader.
// Pass NULL to use the libc's default allocator.
// @return A state for incremental reading.
// It should be freed with `yyjson_incr_free()`.
// NULL is returned if memory allocation fails.
//
//go:linkname YyjsonIncrNew C.yyjson_incr_new
func YyjsonIncrNew(buf *c.Char, buf_len c.SizeT, flg YyjsonReadFlag, alc *YyjsonAlc) *YyjsonIncrState

// Performs incremental read of up to `len` bytes.
//
// If NULL is returned and `err->code` is set to `YYJSON_READ_ERROR_MORE`, it
// indicates that more data is required to continue parsing. Then, call this
// function again with incremented `len`. Continue until a document is returned or
// an error other than `YYJSON_READ_ERROR_MORE` is returned.
//
// Note: Parsing in very small increments is not efficient. An increment of
// several kilobytes or megabytes is recommended.
//
// @param state The state for incremental reading, created using
// `yyjson_incr_new()`.
// @param len The number of bytes of JSON data available to parse.
// If `len` is 0, returns NULL.
// @param err A pointer to receive error information.
// @return A new JSON document, or NULL if an error occurs.
// When the document is no longer needed, it should be freed with
// `yyjson_doc_free()`.
//
// llgo:link (*YyjsonIncrState).YyjsonIncrRead C.yyjson_incr_read
func (self *YyjsonIncrState) YyjsonIncrRead(len c.SizeT, err *YyjsonReadErr) *YyjsonDoc {
	return nil
}

// Release the incremental read state and free the memory.
//
// llgo:link (*YyjsonIncrState).YyjsonIncrFree C.yyjson_incr_free
func (self *YyjsonIncrState) YyjsonIncrFree() {
}

// Read a JSON number.
//
// This function is thread-safe when data is not modified by other threads.
//
// @param dat The JSON data (UTF-8 without BOM), null-terminator is required.
// If `dat` is NULL, returns NULL.
// @param val The output value where result is stored.
// If `val` is NULL, returns NULL.
// The value will hold either UINT or SINT or REAL number;
// @param flg The JSON read options.
// Multiple options can be combined with `|` operator. 0 means no options.
// Supports `YYJSON_READ_NUMBER_AS_RAW` and `YYJSON_READ_ALLOW_INF_AND_NAN`.
// @param alc The memory allocator used for long number.
// It is only used when the built-in floating point reader is disabled.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return If successful, a pointer to the character after the last character
// used in the conversion, NULL if an error occurs.
//
//go:linkname YyjsonReadNumber C.yyjson_read_number
func YyjsonReadNumber(dat *c.Char, val *YyjsonVal, flg YyjsonReadFlag, alc *YyjsonAlc, err *YyjsonReadErr) *c.Char

// Write a document to JSON string with options.
//
// This function is thread-safe when:
// The `alc` is thread-safe or NULL.
//
// @param doc The JSON document.
// If `doc` is NULL or has no root, returns NULL.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param len A pointer to receive output length in bytes (not including the
// null-terminator). Pass NULL if you don't need length information.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON string, or NULL if an error occurs.
// This string is encoded as UTF-8 with a null-terminator.
// When it's no longer needed, it should be freed with free() or alc->free().
//
// llgo:link (*YyjsonDoc).YyjsonWriteOpts C.yyjson_write_opts
func (self *YyjsonDoc) YyjsonWriteOpts(flg YyjsonWriteFlag, alc *YyjsonAlc, len *c.SizeT, err *YyjsonWriteErr) *c.Char {
	return nil
}

// Write a document to JSON file with options.
//
// This function is thread-safe when:
// 1. The file is not accessed by other threads.
// 2. The `alc` is thread-safe or NULL.
//
// @param path The JSON file's path.
// This should be a null-terminated string using the system's native encoding.
// If `path` is NULL or invalid, returns false.
// If the file is not empty, its content is discarded.
// @param doc The JSON document.
// If `doc` is NULL or has no root, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonWriteFile C.yyjson_write_file
func YyjsonWriteFile(path *c.Char, doc *YyjsonDoc, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a document to file pointer with options.
//
// @param fp The file pointer.
// The data will be written to the current position of the file.
// If `fp` is NULL or invalid, returns false.
// @param doc The JSON document.
// If `doc` is NULL or has no root, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonWriteFp C.yyjson_write_fp
func YyjsonWriteFp(fp *c.FILE, doc *YyjsonDoc, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a document into a buffer.
//
// This function does not allocate memory, but the buffer must be larger than the
// final JSON size to allow temporary space. See `API.md` for details.
//
// @param buf The output buffer.
// If `buf` is NULL, returns 0.
// @param buf_len The buffer length.
// If `buf_len` is too small, returns 0.
// @param doc The JSON document.
// If `doc` is NULL or has no root, returns 0.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return The number of bytes written (excluding the null terminator),
// or 0 on failure.
//
//go:linkname YyjsonWriteBuf C.yyjson_write_buf
func YyjsonWriteBuf(buf *c.Char, buf_len c.SizeT, doc *YyjsonDoc, flg YyjsonWriteFlag, err *YyjsonWriteErr) c.SizeT

// Write a document to JSON string with options.
//
// This function is thread-safe when:
// 1. The `doc` is not modified by other threads.
// 2. The `alc` is thread-safe or NULL.
//
// @param doc The mutable JSON document.
// If `doc` is NULL or has no root, returns NULL.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param len A pointer to receive output length in bytes (not including the
// null-terminator). Pass NULL if you don't need length information.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON string, or NULL if an error occurs.
// This string is encoded as UTF-8 with a null-terminator.
// When it's no longer needed, it should be freed with free() or alc->free().
//
// llgo:link (*YyjsonMutDoc).YyjsonMutWriteOpts C.yyjson_mut_write_opts
func (self *YyjsonMutDoc) YyjsonMutWriteOpts(flg YyjsonWriteFlag, alc *YyjsonAlc, len *c.SizeT, err *YyjsonWriteErr) *c.Char {
	return nil
}

// Write a document to JSON file with options.
//
// This function is thread-safe when:
// 1. The file is not accessed by other threads.
// 2. The `doc` is not modified by other threads.
// 3. The `alc` is thread-safe or NULL.
//
// @param path The JSON file's path.
// This should be a null-terminated string using the system's native encoding.
// If `path` is NULL or invalid, returns false.
// If the file is not empty, its content is discarded.
// @param doc The mutable JSON document.
// If `doc` is NULL or has no root, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonMutWriteFile C.yyjson_mut_write_file
func YyjsonMutWriteFile(path *c.Char, doc *YyjsonMutDoc, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a document to file pointer with options.
//
// @param fp The file pointer.
// The data will be written to the current position of the file.
// If `fp` is NULL or invalid, returns false.
// @param doc The mutable JSON document.
// If `doc` is NULL or has no root, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonMutWriteFp C.yyjson_mut_write_fp
func YyjsonMutWriteFp(fp *c.FILE, doc *YyjsonMutDoc, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a document into a buffer.
//
// This function does not allocate memory, but the buffer must be larger than the
// final JSON size to allow temporary space. See `API.md` for details.
//
// @param buf The output buffer.
// If `buf` is NULL, returns 0.
// @param buf_len The buffer length.
// If `buf_len` is too small, returns 0.
// @param doc The JSON document.
// If `doc` is NULL or has no root, returns 0.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return The number of bytes written (excluding the null terminator),
// or 0 on failure.
//
//go:linkname YyjsonMutWriteBuf C.yyjson_mut_write_buf
func YyjsonMutWriteBuf(buf *c.Char, buf_len c.SizeT, doc *YyjsonMutDoc, flg YyjsonWriteFlag, err *YyjsonWriteErr) c.SizeT

// Write a value to JSON string with options.
//
// This function is thread-safe when:
// The `alc` is thread-safe or NULL.
//
// @param val The JSON root value.
// If `val` is NULL, returns NULL.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param len A pointer to receive output length in bytes (not including the
// null-terminator). Pass NULL if you don't need length information.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON string, or NULL if an error occurs.
// This string is encoded as UTF-8 with a null-terminator.
// When it's no longer needed, it should be freed with free() or alc->free().
//
// llgo:link (*YyjsonVal).WriteOpts C.yyjson_val_write_opts
func (self *YyjsonVal) WriteOpts(flg YyjsonWriteFlag, alc *YyjsonAlc, len *c.SizeT, err *YyjsonWriteErr) *c.Char {
	return nil
}

// Write a value to JSON file with options.
//
// This function is thread-safe when:
// 1. The file is not accessed by other threads.
// 2. The `alc` is thread-safe or NULL.
//
// @param path The JSON file's path.
// This should be a null-terminated string using the system's native encoding.
// If `path` is NULL or invalid, returns false.
// If the file is not empty, its content is discarded.
// @param val The JSON root value.
// If `val` is NULL, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonValWriteFile C.yyjson_val_write_file
func YyjsonValWriteFile(path *c.Char, val *YyjsonVal, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a value to file pointer with options.
//
// @param fp The file pointer.
// The data will be written to the current position of the file.
// If `fp` is NULL or invalid, returns false.
// @param val The JSON root value.
// If `val` is NULL, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonValWriteFp C.yyjson_val_write_fp
func YyjsonValWriteFp(fp *c.FILE, val *YyjsonVal, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a value into a buffer.
//
// This function does not allocate memory, but the buffer must be larger than the
// final JSON size to allow temporary space. See `API.md` for details.
//
// @param buf The output buffer.
// If `buf` is NULL, returns 0.
// @param buf_len The buffer length.
// If `buf_len` is too small, returns 0.
// @param val The JSON root value.
// If `val` is NULL, returns 0.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return The number of bytes written (excluding the null terminator),
// or 0 on failure.
//
//go:linkname YyjsonValWriteBuf C.yyjson_val_write_buf
func YyjsonValWriteBuf(buf *c.Char, buf_len c.SizeT, val *YyjsonVal, flg YyjsonWriteFlag, err *YyjsonWriteErr) c.SizeT

// Write a value to JSON string with options.
//
// This function is thread-safe when:
// 1. The `val` is not modified by other threads.
// 2. The `alc` is thread-safe or NULL.
//
// @param val The mutable JSON root value.
// If `val` is NULL, returns NULL.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param len A pointer to receive output length in bytes (not including the
// null-terminator). Pass NULL if you don't need length information.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return A new JSON string, or NULL if an error occurs.
// This string is encoded as UTF-8 with a null-terminator.
// When it's no longer needed, it should be freed with free() or alc->free().
//
// llgo:link (*YyjsonMutVal).WriteOpts C.yyjson_mut_val_write_opts
func (self *YyjsonMutVal) WriteOpts(flg YyjsonWriteFlag, alc *YyjsonAlc, len *c.SizeT, err *YyjsonWriteErr) *c.Char {
	return nil
}

// Write a value to JSON file with options.
//
// This function is thread-safe when:
// 1. The file is not accessed by other threads.
// 2. The `val` is not modified by other threads.
// 3. The `alc` is thread-safe or NULL.
//
// @param path The JSON file's path.
// This should be a null-terminated string using the system's native encoding.
// If `path` is NULL or invalid, returns false.
// If the file is not empty, its content is discarded.
// @param val The mutable JSON root value.
// If `val` is NULL, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonMutValWriteFile C.yyjson_mut_val_write_file
func YyjsonMutValWriteFile(path *c.Char, val *YyjsonMutVal, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a value to file pointer with options.
//
// @param fp The file pointer.
// The data will be written to the current position of the file.
// If `fp` is NULL or invalid, returns false.
// @param val The mutable JSON root value.
// If `val` is NULL, returns false.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param alc The memory allocator used by JSON writer.
// Pass NULL to use the libc's default allocator.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return true if successful, false if an error occurs.
//
// @warning On 32-bit operating system, files larger than 2GB may fail to write.
//
//go:linkname YyjsonMutValWriteFp C.yyjson_mut_val_write_fp
func YyjsonMutValWriteFp(fp *c.FILE, val *YyjsonMutVal, flg YyjsonWriteFlag, alc *YyjsonAlc, err *YyjsonWriteErr) bool

// Write a value into a buffer.
//
// This function does not allocate memory, but the buffer must be larger than the
// final JSON size to allow temporary space. See `API.md` for details.
//
// @param buf The output buffer.
// If `buf` is NULL, returns 0.
// @param buf_len The buffer length.
// If `buf_len` is too small, returns 0.
// @param val The JSON root value.
// If `val` is NULL, returns 0.
// @param flg The JSON write options.
// Multiple options can be combined with `|` operator. 0 means no options.
// @param err A pointer to receive error information.
// Pass NULL if you don't need error information.
// @return The number of bytes written (excluding the null terminator),
// or 0 on failure.
//
//go:linkname YyjsonMutValWriteBuf C.yyjson_mut_val_write_buf
func YyjsonMutValWriteBuf(buf *c.Char, buf_len c.SizeT, val *YyjsonMutVal, flg YyjsonWriteFlag, err *YyjsonWriteErr) c.SizeT

// Write a JSON number.
//
// @param val A JSON number value to be converted to a string.
// If `val` is invalid, returns NULL.
// @param buf A buffer to store the resulting null-terminated string.
// If `buf` is NULL, returns NULL.
// For integer values, the buffer must be at least 21 bytes.
// For floating-point values, the buffer must be at least 40 bytes.
// @return On success, returns a pointer to the character after the last
// written character. On failure, returns NULL.
// @note
// - This function is thread-safe and does not allocate memory
// (when `YYJSON_DISABLE_FAST_FP_CONV` is not defined).
// - This function will fail and return NULL only in the following cases:
// 1) `val` or `buf` is NULL;
// 2) `val` is not a number type;
// 3) `val` is `inf` or `nan`, and non-standard JSON is explicitly disabled
// via the `YYJSON_DISABLE_NON_STANDARD` flag.
//
// llgo:link (*YyjsonVal).YyjsonWriteNumber C.yyjson_write_number
func (self *YyjsonVal) YyjsonWriteNumber(buf *c.Char) *c.Char {
	return nil
}

// Set the string pool size for a mutable document.
// This function does not allocate memory immediately, but uses the size when
// the next memory allocation is needed.
//
// If the caller knows the approximate bytes of strings that the document needs to
// store (e.g. copy string with `yyjson_mut_strcpy` function), setting a larger
// size can avoid multiple memory allocations and improve performance.
//
// @param doc The mutable document.
// @param len The desired string pool size in bytes (total string length).
// @return true if successful, false if size is 0 or overflow.
//
// llgo:link (*YyjsonMutDoc).SetStrPoolSize C.yyjson_mut_doc_set_str_pool_size
func (self *YyjsonMutDoc) SetStrPoolSize(len c.SizeT) bool {
	return false
}

// Set the value pool size for a mutable document.
// This function does not allocate memory immediately, but uses the size when
// the next memory allocation is needed.
//
// If the caller knows the approximate number of values that the document needs to
// store (e.g. create new value with `yyjson_mut_xxx` functions), setting a larger
// size can avoid multiple memory allocations and improve performance.
//
// @param doc The mutable document.
// @param count The desired value pool size (number of `yyjson_mut_val`).
// @return true if successful, false if size is 0 or overflow.
//
// llgo:link (*YyjsonMutDoc).SetValPoolSize C.yyjson_mut_doc_set_val_pool_size
func (self *YyjsonMutDoc) SetValPoolSize(count c.SizeT) bool {
	return false
}

// Release the JSON document and free the memory.
// After calling this function, the `doc` and all values from the `doc` are no
// longer available. This function will do nothing if the `doc` is NULL.
//
// llgo:link (*YyjsonMutDoc).Free C.yyjson_mut_doc_free
func (self *YyjsonMutDoc) Free() {
}

// Creates and returns a new mutable JSON document, returns NULL on error.
// If allocator is NULL, the default allocator will be used.
//
// llgo:link (*YyjsonAlc).YyjsonMutDocNew C.yyjson_mut_doc_new
func (self *YyjsonAlc) YyjsonMutDocNew() *YyjsonMutDoc {
	return nil
}

// Copies and returns a new mutable document from input, returns NULL on error.
// This makes a `deep-copy` on the immutable document.
// If allocator is NULL, the default allocator will be used.
// @note `imut_doc` -> `mut_doc`.
//
// llgo:link (*YyjsonDoc).MutCopy C.yyjson_doc_mut_copy
func (self *YyjsonDoc) MutCopy(alc *YyjsonAlc) *YyjsonMutDoc {
	return nil
}

// Copies and returns a new mutable document from input, returns NULL on error.
// This makes a `deep-copy` on the mutable document.
// If allocator is NULL, the default allocator will be used.
// @note `mut_doc` -> `mut_doc`.
//
// llgo:link (*YyjsonMutDoc).MutCopy C.yyjson_mut_doc_mut_copy
func (self *YyjsonMutDoc) MutCopy(alc *YyjsonAlc) *YyjsonMutDoc {
	return self
}

// Copies and returns a new mutable value from input, returns NULL on error.
// This makes a `deep-copy` on the immutable value.
// The memory is managed by the mutable document.
// @note `imut_val` -> `mut_val`.
//
// llgo:link (*YyjsonMutDoc).YyjsonValMutCopy C.yyjson_val_mut_copy
func (self *YyjsonMutDoc) YyjsonValMutCopy(val *YyjsonVal) *YyjsonMutVal {
	return nil
}

// Copies and returns a new mutable value from input, returns NULL on error.
// This makes a `deep-copy` on the mutable value.
// The memory is managed by the mutable document.
// @note `mut_val` -> `mut_val`.
// @warning This function is recursive and may cause a stack overflow
// if the object level is too deep.
//
// llgo:link (*YyjsonMutDoc).YyjsonMutValMutCopy C.yyjson_mut_val_mut_copy
func (self *YyjsonMutDoc) YyjsonMutValMutCopy(val *YyjsonMutVal) *YyjsonMutVal {
	return nil
}

// Copies and returns a new immutable document from input,
// returns NULL on error. This makes a `deep-copy` on the mutable document.
// The returned document should be freed with `yyjson_doc_free()`.
// @note `mut_doc` -> `imut_doc`.
// @warning This function is recursive and may cause a stack overflow
// if the object level is too deep.
//
// llgo:link (*YyjsonMutDoc).ImutCopy C.yyjson_mut_doc_imut_copy
func (self *YyjsonMutDoc) ImutCopy(alc *YyjsonAlc) *YyjsonDoc {
	return nil
}

// Copies and returns a new immutable document from input,
// returns NULL on error. This makes a `deep-copy` on the mutable value.
// The returned document should be freed with `yyjson_doc_free()`.
// @note `mut_val` -> `imut_doc`.
// @warning This function is recursive and may cause a stack overflow
// if the object level is too deep.
//
// llgo:link (*YyjsonMutVal).ImutCopy C.yyjson_mut_val_imut_copy
func (self *YyjsonMutVal) ImutCopy(alc *YyjsonAlc) *YyjsonDoc {
	return nil
}

// Creates and returns a patched JSON value (RFC 6902).
// The memory of the returned value is allocated by the `doc`.
// The `err` is used to receive error information, pass NULL if not needed.
// Returns NULL if the patch could not be applied.
//
// llgo:link (*YyjsonMutDoc).YyjsonPatch C.yyjson_patch
func (self *YyjsonMutDoc) YyjsonPatch(orig *YyjsonVal, patch *YyjsonVal, err *YyjsonPatchErr) *YyjsonMutVal {
	return nil
}

// Creates and returns a patched JSON value (RFC 6902).
// The memory of the returned value is allocated by the `doc`.
// The `err` is used to receive error information, pass NULL if not needed.
// Returns NULL if the patch could not be applied.
//
// llgo:link (*YyjsonMutDoc).YyjsonMutPatch C.yyjson_mut_patch
func (self *YyjsonMutDoc) YyjsonMutPatch(orig *YyjsonMutVal, patch *YyjsonMutVal, err *YyjsonPatchErr) *YyjsonMutVal {
	return nil
}

// Creates and returns a merge-patched JSON value (RFC 7386).
// The memory of the returned value is allocated by the `doc`.
// Returns NULL if the patch could not be applied.
//
// @warning This function is recursive and may cause a stack overflow if the
// object level is too deep.
//
// llgo:link (*YyjsonMutDoc).YyjsonMergePatch C.yyjson_merge_patch
func (self *YyjsonMutDoc) YyjsonMergePatch(orig *YyjsonVal, patch *YyjsonVal) *YyjsonMutVal {
	return nil
}

// Creates and returns a merge-patched JSON value (RFC 7386).
// The memory of the returned value is allocated by the `doc`.
// Returns NULL if the patch could not be applied.
//
// @warning This function is recursive and may cause a stack overflow if the
// object level is too deep.
//
// llgo:link (*YyjsonMutDoc).YyjsonMutMergePatch C.yyjson_mut_merge_patch
func (self *YyjsonMutDoc) YyjsonMutMergePatch(orig *YyjsonMutVal, patch *YyjsonMutVal) *YyjsonMutVal {
	return nil
}
func (p *YyjsonValUni) XGof_ref_u64() *c.Uint64T {
	return (*c.Uint64T)(unsafe.Pointer(p))
}
func (p *YyjsonValUni) XGof_ref_i64() *c.Int64T {
	return (*c.Int64T)(unsafe.Pointer(p))
}
func (p *YyjsonValUni) XGof_ref_f64() *c.Double {
	return (*c.Double)(unsafe.Pointer(p))
}
func (p *YyjsonValUni) XGof_ref_str() **c.Char {
	return (**c.Char)(unsafe.Pointer(p))
}
func (p *YyjsonValUni) XGof_ref_ptr() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(p))
}
func (p *YyjsonValUni) XGof_ref_ofs() *c.SizeT {
	return (*c.SizeT)(unsafe.Pointer(p))
}

// llgo:link (*YyjsonVal).UnsafeYyjsonEquals C.unsafe_yyjson_equals
func (self *YyjsonVal) UnsafeYyjsonEquals(rhs *YyjsonVal) bool {
	return false
}

// Ensures the capacity to at least equal to the specified byte length.
//
// llgo:link (*YyjsonStrPool).UnsafeYyjsonStrPoolGrow C.unsafe_yyjson_str_pool_grow
func (self *YyjsonStrPool) UnsafeYyjsonStrPoolGrow(alc *YyjsonAlc, len c.SizeT) bool {
	return false
}

// Ensures the capacity to at least equal to the specified value count.
//
// llgo:link (*YyjsonValPool).UnsafeYyjsonValPoolGrow C.unsafe_yyjson_val_pool_grow
func (self *YyjsonValPool) UnsafeYyjsonValPoolGrow(alc *YyjsonAlc, count c.SizeT) bool {
	return false
}

// llgo:link (*YyjsonMutVal).UnsafeYyjsonMutEquals C.unsafe_yyjson_mut_equals
func (self *YyjsonMutVal) UnsafeYyjsonMutEquals(rhs *YyjsonMutVal) bool {
	return false
}

// require: val != NULL, *ptr == '/', len > 0
//
// llgo:link (*YyjsonVal).UnsafeYyjsonPtrGetx C.unsafe_yyjson_ptr_getx
func (self *YyjsonVal) UnsafeYyjsonPtrGetx(ptr *c.Char, len c.SizeT, err *YyjsonPtrErr) *YyjsonVal {
	return self
}

// require: val != NULL, *ptr == '/', len > 0
//
// llgo:link (*YyjsonMutVal).UnsafeYyjsonMutPtrGetx C.unsafe_yyjson_mut_ptr_getx
func (self *YyjsonMutVal) UnsafeYyjsonMutPtrGetx(ptr *c.Char, len c.SizeT, ctx *YyjsonPtrCtx, err *YyjsonPtrErr) *YyjsonMutVal {
	return self
}

// require: val/new_val/doc != NULL, *ptr == '/', len > 0
//
// llgo:link (*YyjsonMutVal).UnsafeYyjsonMutPtrPutx C.unsafe_yyjson_mut_ptr_putx
func (self *YyjsonMutVal) UnsafeYyjsonMutPtrPutx(ptr *c.Char, len c.SizeT, new_val *YyjsonMutVal, doc *YyjsonMutDoc, create_parent bool, insert_new bool, ctx *YyjsonPtrCtx, err *YyjsonPtrErr) bool {
	return false
}

// require: val/err != NULL, *ptr == '/', len > 0
//
// llgo:link (*YyjsonMutVal).UnsafeYyjsonMutPtrReplacex C.unsafe_yyjson_mut_ptr_replacex
func (self *YyjsonMutVal) UnsafeYyjsonMutPtrReplacex(ptr *c.Char, len c.SizeT, new_val *YyjsonMutVal, ctx *YyjsonPtrCtx, err *YyjsonPtrErr) *YyjsonMutVal {
	return self
}

// require: val/err != NULL, *ptr == '/', len > 0
//
// llgo:link (*YyjsonMutVal).UnsafeYyjsonMutPtrRemovex C.unsafe_yyjson_mut_ptr_removex
func (self *YyjsonMutVal) UnsafeYyjsonMutPtrRemovex(ptr *c.Char, len c.SizeT, ctx *YyjsonPtrCtx, err *YyjsonPtrErr) *YyjsonMutVal {
	return self
}
